### ISSUE TITLE
Absorbing state fix

### ISSUE THREAD

**Issue by qxcv** [HumanCompatibleAI/imitation#40] opened 2019-07-09 23:20 UTC
For environments that can terminate before some fixed horizon, it would be good to have the absorbing state fix from [discriminator-actor-critic](https://openreview.net/pdf?id=Hk4fpoA5Km).

Programatically, I expect we could do this by making a new env wrapper that always produces a final `(s_absorb,a_0, s_absorb)` transition at the end of each trajectory before propagating `done=True` up. `s_absorb` could be represented by a zero vector of size `d_obs`, or by a zero vector of size `d_obs` with an extra `1` flag appended to the end to signal that it's terminal. The only really tricky bit would be ensuring that `a_0` is always the same for the last trajectory, which might require some changes to the rollout code.

**Comment by AdamGleave** [comment] 2019-07-10 17:43
A fix for this issue would certainly be valuable. I'm not sure on the details of how best to implement it.

For reproducibility, we should definitely make this optional, although perhaps the default.

If I understand the fix correctly, we're effectively learning just one additional parameter: the reward in an absorbing state. And then to compute returns, we're summing the discounted absorbing reward up over the remaining (possibly infinite) steps in the horizon.

This suggests an implementation where we instead have a wrapper around the `RewardNet` that adds this extra parameter and, for terminal state transitions, computes the terminal return. This might require adding some extra placeholders, e.g. for the `dones` flags and the number of remaining timesteps.

This feels cleaner to me than changing the observation space, where I'd be concerned the reward model might have smoothness constraints that make it unable to assign arbitrary values to the terminal reward without also changing the reward assigned to nearby states. Near-zero states especially often occur naturally.

**Comment by qxcv** [comment] 2019-07-15 23:59
A bit late, but…

> I'd be concerned the reward model might have smoothness constraints that make it unable to assign arbitrary values to the terminal reward without also changing the reward assigned to nearby states

Ah, that's why I suggested adding the extra 1 indicator at the end for absorbing states (which would be 0 in non-absorbing states). Unless the model has extremely strong smoothness constraints, it should be able to get a lot out of a single dimension that changes value completely in absorbing states. Doing it this way also means that we don't need a wrapper that messes with TF graphs to introduce a new parameter & conditional, which is possibly (?) harder than just changing observations. Then again, changing observations would get harder for image spaces (where in the image do you tack on the extra dim?), so perhaps the extra parameter way is more general :man_shrugging:

**Comment by AdamGleave** [comment] 2019-07-16 09:47
> Ah, that's why I suggested adding the extra 1 indicator at the end for absorbing states (which would be 0 in non-absorbing states). Unless the model has extremely strong smoothness constraints, it should be able to get a lot out of a single dimension that changes value completely in absorbing states. Doing it this way also means that we don't need a wrapper that messes with TF graphs to introduce a new parameter & conditional, which is possibly (?) harder than just changing observations. Then again, changing observations would get harder for image spaces (where in the image do you tack on the extra dim?), so perhaps the extra parameter way is more general

Makes sense; I think adding an extra dimension would work in most (non-image) based spaces. The wrapper seems fairly simple to me although there might be some gremlin I've missed. Main downside of wrapper is it'd need to be tied to a particular ML framework e.g. TensorFlow, but then `RewardNet` already is tightly coupled.

**Comment by AdamGleave** [comment] 2020-05-08 03:29
@qxcv do you think https://github.com/HumanCompatibleAI/imitation/pull/184 fixes this problem? I designed it mainly to get potential shaping right, but I've also made `RewardNet` optionally take (if `use_dones=True`) the episode termination as a single-dimensional input to the MLP.

**Comment by qxcv** [comment] 2020-05-08 17:16
It should do. Perhaps it's worth having Pedro re-run AIRL/GAIL after #184 is merged (both with and without the `use_dones` flag) to check whether it fixes issues with `EarlyTerm+`/`EarlyTerm-`?

**Comment by AdamGleave** [comment] 2020-05-09 01:35
Good idea, @pedrofreire do you think you could check if `use_dones` fixes early termination bias? I guess this may be non-trivial for you since your implementation has diverged from `imitation`.

**Comment by AdamGleave** [comment] 2020-05-09 01:35
I'm going to close this optimistically and we can reopen it if this continues to be a problem in the future.

**Closed by AdamGleave** 2020-05-09 01:35 UTC
