### ISSUE TITLE
Expert dataset

### ISSUE THREAD

**Issue by DAOvb** [HumanCompatibleAI/imitation#329] opened 2021-08-31 12:08 UTC
Hi guys! I've got a dataset in .pkl file, that the same as yours final.pkl. How i could wrap it into expert dataset for Behavioural Cloning?

**Comment by ejnnr** [comment] 2021-08-31 13:08
If you just want to train BC on a different file of expert trajectories than the default, then something like
```
python -m imitation.scripts.train_bc with cartpole expert_data_src=path/to/file.pkl
```
should work (you'll have to set the right environment of course).

If you want to do something more complicated, you can see here and in the following lines how the BC training script transforms the dataset of expert trajectories before passing it to BC:
https://github.com/HumanCompatibleAI/imitation/blob/1ebbf513b525eeb1bbc323da858e60a8941ccd1a/src/imitation/scripts/train_bc.py#L108

**Comment by DAOvb** [comment] 2021-08-31 16:36
Thank you! I have created an expert dataset but now i have a new problem: i pretrained some policy (clearly sb3.ppo.MlpPolicy) but after that i can't use it in sb3.PPO model because of some kwargs excepts. 
Exception is: 
TypeError: forward() got an unexpected keyword argument 'use_sde'

**Comment by ejnnr** [comment] 2021-08-31 17:09
I don't think we can answer that without more details (at least I don't know what might be happening here). Ideally, a minimal example that produces this error, but at least a backtrace and a code snippet where the error is triggered.

**Comment by DAOvb** [comment] 2021-08-31 17:15
Code where i clone behaviour:

bc_trainer = bc.BC(venv.observation_space, venv.action_space, policy_class = sb3.ppo.MlpPolicy, expert_data=transitions)
bc_trainer.train(n_epochs=1)

After that i save and load policy:
bc_trainer.save_policy('policy')
policy = bc.reconstruct_policy('policy')
After that i use that policy as the policy for PPO model
model = sb3.PPO(policy, venv, verbose=1,tensorboard_log = 'log')
model.learn(total_timesteps=N*10, log_interval=10)

**Comment by DAOvb** [comment] 2021-08-31 17:16
![image](https://user-images.githubusercontent.com/84871302/131547195-48a775ee-ca69-4138-9f46-90ff1b46a2c5.png)
![image](https://user-images.githubusercontent.com/84871302/131547235-8b3da53c-fd70-40ab-a672-01bc33192583.png)

Error screenshots

**Comment by AdamGleave** [comment] 2021-08-31 17:36
That's odd, `sb3.ppo.MlpPolicy` does take a `use_sde` flag in `__init__`, so that should work. It's not clear to me why this ends up as `forward`.

If you can provide a complete script that we can run to replicate the error I'm happy to take a look.

**Comment by ejnnr** [comment] 2021-08-31 18:04
I think the issue is that `PPO` doesn't take an instantiated policy as its first argument but rather a policy class (or the name of one). See https://stable-baselines3.readthedocs.io/en/master/modules/ppo.html#stable_baselines3.ppo.PPO.

Once that's fixed, the issue is basically the same as in #283, namely how to load an existing policy into an SB3 algorithm.

**Comment by AdamGleave** [comment] 2021-08-31 18:11
Oh, right, good catch! Yeah, pass in policy class, then override the policy and model on the RL algorithm.

You could also maybe make a stub policy class that just returns `policy`.

**Comment by DAOvb** [comment] 2021-08-31 18:33
Thank you guys! But there is new mistakes occur 
![image](https://user-images.githubusercontent.com/84871302/131557296-dc9f956c-45d2-4a6e-98b8-a7bf3a443f16.png)

**Comment by AdamGleave** [comment] 2021-08-31 18:35
Just merged a PR that upgrades to a newer version of SB3 where these logging issues are fixed, can you try checking out master and `pip install --upgrade .` to get the latest version of SB3?

**Comment by DAOvb** [comment] 2021-08-31 18:43
So thank u guys! All problems are solved.

**Comment by AdamGleave** [comment] 2021-08-31 18:53
Glad to hear it. Closing the issue, enjoy the repo :)

**Closed by AdamGleave** 2021-08-31 18:53 UTC
