### ISSUE TITLE
comptibilte between gym and gymnasium 

### ISSUE THREAD

**Issue by Oualisof** [HumanCompatibleAI/imitation#736] opened 2023-07-03 15:22 UTC
C:\Users\ouali\anaconda3\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(
C:\Users\ouali\anaconda3\lib\site-packages\stable_baselines3\common\evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(

Traceback (most recent call last):

  File "C:\Users\ouali\OneDrive\Bureau\imitation-master\imitation-master\examples\gymmm.py", line 44, in <module>
    bc_trainer = bc.BC(

  File "C:\Users\ouali\anaconda3\lib\site-packages\imitation\algorithms\bc.py", line 328, in __init__
    policy = policy_base.FeedForward32Policy(

  File "C:\Users\ouali\anaconda3\lib\site-packages\imitation\policies\base.py", line 72, in __init__
    super().__init__(*args, **kwargs, net_arch=[32, 32])

  File "C:\Users\ouali\anaconda3\lib\site-packages\stable_baselines3\common\policies.py", line 481, in __init__
    self.features_extractor = self.make_features_extractor()

  File "C:\Users\ouali\anaconda3\lib\site-packages\stable_baselines3\common\policies.py", line 120, in make_features_extractor
    return self.features_extractor_class(self.observation_space, **self.features_extractor_kwargs)

  File "C:\Users\ouali\anaconda3\lib\site-packages\stable_baselines3\common\torch_layers.py", line 41, in __init__
    super().__init__(observation_space, get_flattened_obs_dim(observation_space))

  File "C:\Users\ouali\anaconda3\lib\site-packages\stable_baselines3\common\preprocessing.py", line 185, in get_flattened_obs_dim
    return spaces.utils.flatdim(observation_space)

  File "C:\Users\ouali\anaconda3\lib\functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)

  File "C:\Users\ouali\anaconda3\lib\site-packages\gymnasium\spaces\utils.py", line 53, in flatdim
    if space.is_np_flattenable is False:

AttributeError: 'Box' object has no attribute 'is_np_flattenable'

when i run the train with BC algorthims this error appair in my code i try to fix it with changing my envorement in gymnasium i alos have an error with the gym box

**Comment by RedTachyon** [comment] 2023-07-03 17:47
Make sure you use`stable-baselines3==1.7.0` when using gym and the current version of `imitation`. Soon-ish (#735) everything should nicely with the new version of SB3 and Gymnasium

**Comment by roeslib** [comment] 2023-07-12 23:13
I tried to used sb3_contrib with the method MaskablePPO (https://github.com/Stable-Baselines-Team/stable-baselines3-contrib)  but it uses stable-baselines3==2.0.0, my use case needs an invalid action masking otherwise the learning will be slower. Is there a way to use the libraries of this repository with the version 2.0.0? or could you please give me a hint how can I implement the invalid action masking in the PPO method of the version 1.7.0?

**Comment by AdamGleave** [comment] 2023-09-09 03:27
Duplicate of #734, closing. Gymnasium support is on the roadmap and should be here in the next few weeks.

**Closed by AdamGleave** 2023-09-09 03:27 UTC
Labels: bug
