### ISSUE TITLE
<help>ValueError:  The parameter probs has invalid values when using custom environment

### ISSUE THREAD

**Issue by RenoMang** [HumanCompatibleAI/imitation#321] opened 2021-08-23 20:40 UTC
I create a custom gym environment and use stable baseline to generate expert trajectories. Then I hope to use AIRL from imitation to generate apprentice policies.

Part of my code is:
```Python
gym.envs.register(
     id='CustomGame-v0',
     entry_point='gym.envs.classic_control:CustomGame',
     max_episode_steps=200,
     kwargs={'mode' : 0},
)
env = util.make_vec_env('CustomGame-v0', n_envs=1, parallel=False)

model = PPO('MlpPolicy', env, verbose=1).learn(40000)
env.reset()

orig_rollout = rollout.generate_transitions(
        model,
        env,
        n_timesteps=1000,
        deterministic_policy=True,
        rng=np.random.RandomState(0),
    )

tempdir = tempfile.TemporaryDirectory(prefix="money_only")
tempdir_path = pathlib.Path(tempdir.name)

logger.configure(tempdir_path / "AIRL/")
airl_trainer = adversarial.AIRL(
    env,
    expert_data=orig_rollout,
    expert_batch_size=32,
    gen_algo=sb3.PPO("MlpPolicy", env, verbose=1, n_steps=1024),
)
airl_trainer.train(total_timesteps=2048)
```

When I run it, it throws the ValueError:  The parameter probs has invalid values.
```
  File "/mnt/d/HEL-intern/IRL-Imitation/AIRL.py", line 42, in <module>
    airl_trainer.train(total_timesteps=2048)
  File "/mnt/d/HEL-intern/IRL-Imitation/.venv/lib/python3.8/site-packages/imitation/algorithms/adversarial.py", line 309, in train
    self.train_disc()
  File "/mnt/d/HEL-intern/IRL-Imitation/.venv/lib/python3.8/site-packages/imitation/algorithms/adversarial.py", line 235, in train_disc
    train_stats = rew_common.compute_train_stats(
  File "/mnt/d/HEL-intern/IRL-Imitation/.venv/lib/python3.8/site-packages/imitation/rewards/common.py", line 135, in compute_train_stats
    label_dist = th.distributions.Bernoulli(disc_logits_gen_is_high)
  File "/mnt/d/HEL-intern/IRL-Imitation/.venv/lib/python3.8/site-packages/torch/distributions/bernoulli.py", line 48, in __init__
    super(Bernoulli, self).__init__(batch_shape, validate_args=validate_args)
  File "/mnt/d/HEL-intern/IRL-Imitation/.venv/lib/python3.8/site-packages/torch/distributions/distribution.py", line 53, in __init__
    raise ValueError("The parameter {} has invalid values".format(param))
ValueError: The parameter probs has invalid values
```

Thanks for any help and reply.

**Comment by AdamGleave** [comment] 2021-08-23 22:14
Duplicate of https://github.com/HumanCompatibleAI/imitation/issues/318, closing

**Closed by AdamGleave** 2021-08-23 22:14 UTC
